name: Build DRK CRM .exe

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Package with PyInstaller
      run: |
        pyinstaller --onefile --windowed drkcrm.py

    - name: Upload .exe
      uses: actions/upload-artifact@v4
      with:
        name: drk-crm-windows-exe
        path: dist/drkcrm.exe
